default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  database: <%= ENV.fetch('POSTGRES_DB_NAME', 'farfetch_default') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432).to_i %>
  pool: 5

development:
  <<: *default
  database: farfetch_development

test:
  <<: *default
  database: farfetch_test<%= ENV.fetch('TEST_ENV_NUMBER', '') %>

production:
  <<: *default
  database: farfetch_production
